# Generated by Django 4.2.3 on 2023-07-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_category_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
